### ISSUE TITLE
500 error on install

### ISSUE THREAD

**Issue by msaltzm1** [alleyinteractive/voicewp#66]
I already have my SSL installed. When I use Plugins>Add New>Upload Plugin  > then choose the voicewp-master.zip, the site returns an HTTP 500 ERROR. I am using AWS Lightsail with the $10 a month instance 1 GB Memory 1 Core Processor 30 GB SSD Disk 2 TB Transfer. Any thoughts on the matter?

**Comment by tomharrigan** [comment]
Yes, you need the Fieldmanager plugin installed, it's a prerequisite. I'll update the plugin tonight so that it doesn't throw a 500. This is definitely a bug and an admin notice is supposed to display notifying the user to install Fieldmanager. Thanks for identifying this and I'll reply here when that fix is up

**Comment by tomharrigan** [comment]
@msaltzm1 the latest update to the plugin resolves the issue. You can download Fieldmanager here https://github.com/alleyinteractive/wordpress-fieldmanager/releases
